### ISSUE TITLE
Terminal logging

### ISSUE THREAD

**Issue by tokejepsen** [abstractfactory/pyblish-nuke#3]
Found that nuke has a nuke.tprint option that prints to the terminal. 

This might be a better option to print with for any outputs (if you aren't using the fronend), as it persists better. Currently the output from Pyblish goes into a script editor (if open), and gets lost when you close the script editor.

**Comment by mottosso** [comment]
Pyblish outputs everything through the Python standard library `logging`. Typically, when you initialise a logger, you implicitly tell it to output to the shell using `sys.stdout` but that's configurable.

Here's how it works.

![](https://docs.python.org/2/_images/logging_flow.png)
https://docs.python.org/2/howto/logging.html#logging-flow

What you could do is to setup a logger to instead output using `nuke.tprint`, or both.

**Comment by mottosso** [comment]
As discussed in the Gitter, the issue was related to the logging level being set too low. The output now prints to both the script editor and terminal. 

Feel free to re-open this otherwise!
